<?php

return [
    'konservasi-penelitian' => 'Research Conservation',
    'nilai-penting' => 'Significance and Utilization',
    'nilai-nilai-penting' => 'Significant Values of Pawon Cave',
    'temukan-kisah' => 'Discover the story of prehistoric humans who once lived in Pawon Cave. Explore history, culture, and archaeological remains in a single educational platform.',
    'nilai-penting-pawon' => 'Significant Values of Pawon Cave',
    'temuan-prasejarah' => 'The prehistoric findings in Pawon Cave and other caves within the Pawon Cave site remain the only known Mesolithic-period remains in West Java. Discoveries over more than a decade have drawn attention from print media, electronic media, and scientists from various disciplines.',
    'hal-itu-berkaitan' => 'This mainly relates to the discovery of prehistoric human remains at the Pawon Cave site. These remains exhibit unique burial characteristics, associated with stone artifacts and various bone fragments from animals and mollusks originating from both freshwater and marine sources—an important phenomenon that warrants further study.',
    'oleh-sebab-itu' => 'Therefore, the discovery of prehistoric humans and culture in Pawon Cave is not the end point of research, but rather the starting point that must continue to be developed to enrich scientific knowledge in Indonesia and globally.',
    'nilai-penting-arkeologi' => 'Scientific Significance in Archaeology',
    'nilai-penting-pengetahuan-arkeologi' => 'Scientific Value in Archaeological Knowledge',
    'teknik-dan-metodologi' => 'Significance in the Development of Research Techniques and Methodologies',
    'pemanfaatan-hasil' => 'Utilization of Scientific Research Outputs',
    'temuan-rangka-manusia' => 'The discovery of human skeletons in Pawon Cave reveals a unique burial pattern—flexed burial—that is rarely found in Indonesia. Other caves showing similar patterns include Song Terus, Song Keplek, Sodong Cave, Lawa Cave, and Marjan Cave, dating back approximately 9,800 years.',
    'rangka-manusia-diperkirakan' => 'The human skeletons in Pawon Cave are estimated to be between 5,600 and 12,000 years old. This enriches archaeological data on ancient burial practices in Southeast Asia, especially during the transition from the late Pleistocene to the early Holocene.',
    'dibandingkan-situs-lainnya' => 'Compared to other cave sites, Pawon Cave shows longer and more diverse habitation traces, ranging from 5,600 to 11,000 years ago, making it one of the key sites in prehistoric studies in the region.',
    'penelitian-sejak-2003' => 'Research at Pawon Cave since 2003, and especially after 2012, has evolved from a preservation focus to an interdisciplinary approach. Disciplines such as geology, paleoclimate studies, and palynology have been involved to understand cave formation and past environments. Sampling techniques for dating analysis have also been applied, using Acetylene (C₂H₂) and Benzene (C₆H₆) methods in laboratories in Bandung and Jakarta.',
    'menjadi-contoh-penting' => 'Pawon Cave serves as an important example of collaboration between the natural and social sciences, considering archaeological data is limited and non-renewable. A well-planned approach allows deeper and more accurate insights, becoming a reference for other prehistoric site studies.',
    'temuan-mencakup' => 'Findings at this site include stone artifacts, bones, shells, food remains, and human skeletons from five different periods. Stratigraphically, Neolithic cultural layers (0–100 cm) and Mesolithic layers (100–320 cm) were found. However, aspects such as diet and life expectancy remain minimally discussed.',
    'odontologi-forensik' => 'Through a Forensic Odontology approach, the analysis of Pawon human teeth and jaws reveals information such as age, sex, dental hygiene, and fiber and starch contents related to dietary patterns. Technologies like 3D CBCT and SEM are used for in-depth analysis of dental calculus, opening new opportunities in archaeological and interdisciplinary research methods.',
    'hasil-arkeologi' => "The archaeological findings at Pawon Cave have been widely utilized, especially in interdisciplinary education. The site's data have been used in four undergraduate theses and one master’s thesis in the Archaeology Department at FIB UI, as well as theses at UGM and Udayana. Interdisciplinary analyses involving Forensic Odontology have also produced around 34 scientific works, including theses, journals, and proceedings at the Faculty of Dentistry, Unpad. Additionally, Pawon Cave data have been utilized in environmental studies, with theses written at UI and ITB, and in tourism development, forming the basis for theses at STP Bandung and Telkom University.",
    'kebanggaan-daerah' => 'Regional Pride and Tourism Destination Development of West Java',
    'sejak-ditemukan-2000' => 'Since its discovery in 2000 and archaeological research starting in 2003, the Pawon Cave site has drawn attention from various groups, from interdisciplinary researchers to local governments. Research conducted by the West Java Archaeological Center uncovered prehistoric cultures that became the basis for tourism development in West Java.',
    'gunung-pawon' => 'Today, Pawon Cave and the Gunung Pawon area have developed into one of the province’s leading tourist attractions, with increasing visitor numbers contributing to local income. Local governments are utilizing this research by revitalizing the site and planning the development of the Pawon Cave Museum.',
    'pengembangan-destinasi' => 'The development of this destination is part of a continuous effort to combine cultural heritage preservation with regional economic potential. Ongoing research and utilization of the site are designed to provide long-term benefits to the community and serve as a source of regional pride for West Java.'
];
